# Default config for src.core.loop.
# Command-line arguments override values here.

task: dabstep
dataset: explore
workspace_dir: outputs/dabstep_cc

category_list: 
  - "Average_Transaction_Value_Stats"
  - "Applicable_Fee_IDs"
  - "Total_Fees_Calculation"

run_name: test_run_name
iterations: 1

manager_url: http://localhost:5005
backend: openai

da_agent:
  # react
  agent_type: react
  model: your_model_name
  api_key: your_api_key
  base_url: your_base_url
  
  temperature: 1.0
  top_p: 1.0
  max_tokens: 16384

  max_turns: 20
  max_workers: 3
  sample_nums: 3

verifier:
  name: supervised
  
skill_manager:
  agent_type: claude_code
  model: claude-sonnet-4-6
  api_key: your_api_key
  base_url: your_base_url
  max_workers: 3